apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.nameSpace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: {{ .Values.app.name }}
